# Only for local 
version: '3.8'

services:
  server:
    build: ./server
    network_mode: "host"  
    environment:
      DB_HOST: localhost  
      DB_PORT: 5432
      DB_DATABASE: flask_demo
      DB_USER: postgres
      DB_PASSWORD: admin

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000